name: Sync Multiple Subtrees to Separate Repos

on:
    push:
        tags:
            - '*'

permissions:
    contents: write
    id-token: write

jobs:
    sync-subtrees:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Configure Git
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    # 一次性配置所有远程仓库
                    git remote add preacher "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/waplar-core/preacher.git"

            -   name: Push Code
                run: |
                    if [[ $GITHUB_REF == refs/tags/* ]]; then
                      TAG=${GITHUB_REF#refs/tags/}
                      git subtree push --prefix=src/Artist/Preacher preacher $TAG
                    else
                      BRANCH=${GITHUB_REF#refs/heads/}
                      git subtree push --prefix=src/Artist/Preacher preacher $BRANCH
                      # 添加其他子目录推送
                    fi
